<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-02T17:27:31 IST" name="Failed suite [Failed suite [Default suite]]" finished-at="2023-07-02T17:28:17 IST" duration-ms="45615">
    <groups>
    </groups>
    <test started-at="2023-07-02T17:27:31 IST" name="Default test(failed)(failed)" finished-at="2023-07-02T17:28:17 IST" duration-ms="45615">
      <class name="workingwithTestNg.TestNgFirstProgram">
        <test-method signature="irctc()[pri:0, instance:workingwithTestNg.TestNgFirstProgram@3c947bc5]" started-at="2023-07-02T17:27:31 IST" name="irctc" finished-at="2023-07-02T17:27:31 IST" duration-ms="13" status="FAIL">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at workingwithTestNg.TestNgFirstProgram.irctc(TestNgFirstProgram.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- irctc -->
        <test-method signature="makeMyTrip()[pri:0, instance:workingwithTestNg.TestNgFirstProgram@3c947bc5]" started-at="2023-07-02T17:27:31 IST" name="makeMyTrip" finished-at="2023-07-02T17:28:17 IST" duration-ms="45536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeMyTrip -->
      </class> <!-- workingwithTestNg.TestNgFirstProgram -->
    </test> <!-- Default test(failed)(failed) -->
  </suite> <!-- Failed suite [Failed suite [Default suite]] -->
</testng-results>
